[package]
name = "atg-conduit"
version = "0.1.0"
edition = "2018"

[dependencies]
carrier             = "0.8.1"
osaka               = "0.2.7"
log                 = "0.4"
prost               = "0.4.0"
env_logger          = "0.6.0"
